/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rollouts, newest first, without wave devices */
        get: {
            parameters: {
                query?: {
                    /** @description active = running, soaking or paused; finished = completed or aborted */
                    state?: "active" | "finished";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The rollouts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rollout"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts, newest first */
        get: {
            parameters: {
                query?: {
                    state?: "open" | "resolved";
                    /** @description Default 50, maximum 200 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The alerts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge an open alert (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The acknowledged alert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        RolloutState: "running" | "soaking" | "paused" | "completed" | "aborted";
        /** @enum {string} */
        RolloutDeviceState: "waiting" | "downloading" | "installing" | "updated" | "rolled_back" | "needs_recovery" | "skipped" | "deferred";
        /** @description Gateways in the rollout by state; they add up to the rollout's size */
        RolloutCounters: {
            updated: number;
            in_progress: number;
            rolled_back: number;
            needs_recovery: number;
            skipped: number;
            deferred: number;
            waiting: number;
        };
        RolloutWave: {
            /** @description Share of the model's gateways updated once this wave finishes */
            percent: number;
            /** @description Present on GET /rollouts/{id} only */
            devices?: {
                sn: string;
                state: components["schemas"]["RolloutDeviceState"];
            }[];
        };
        Rollout: {
            /** @example R-014 */
            id: string;
            model_id: string;
            fw_version: string;
            /** Format: date-time */
            created_at: string;
            /** @description Name of the user who started it */
            created_by: string;
            state: components["schemas"]["RolloutState"];
            /** @description Why the rollout paused itself; null when paused by a person or running */
            pause_reason?: string | null;
            counters: components["schemas"]["RolloutCounters"];
            waves: components["schemas"]["RolloutWave"][];
        };
        /** @enum {string} */
        AlertSeverity: "info" | "warning" | "critical";
        Alert: {
            id: string;
            sn: string;
            /** @example temp_high */
            rule: string;
            severity: components["schemas"]["AlertSeverity"];
            /** @example Temperature 81 °C */
            message: string;
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            resolved_at: string | null;
            /** @description Name of the admin who acknowledged it */
            acked_by: string | null;
            /** Format: date-time */
            acked_at: string | null;
        };
        Error: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description Missing, invalid or expired credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with existing state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
