/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/rollouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rollouts, newest first, without wave devices */
        get: {
            parameters: {
                query?: {
                    /** @description active = running, soaking or paused; finished = completed or aborted */
                    state?: "active" | "finished";
                    /** @description Only rollouts that include this gateway; each wave then lists just that gateway, so the device page can show its own progress */
                    sn?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The rollouts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rollout"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts, newest first */
        get: {
            parameters: {
                query?: {
                    state?: "open" | "resolved";
                    /** @description Default 50, maximum 200 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The alerts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{sn}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a remote action on a gateway (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sn: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActionRequest"];
                };
            };
            responses: {
                /** @description The job that tracks the action */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description action_pending (one of this type is already pending) or device_offline */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A job, polled every 3 s until its state is final */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a job that has not started (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The cancelled job */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download link for the archive a successful logs job uploaded */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A short-lived /dl/{token} link */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobLogs"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description The job did not succeed, or is not a logs job */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/configs/{v}/push/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Who a push of this version would reach, before anyone confirms */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ModelId"];
                    v: components["parameters"]["ConfigVersionNumber"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description How many gateways would get the job and how many of them are offline */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PushPreview"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/configs/{v}/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make this version the model's target and queue it for every gateway (release engineer)
         * @description Afterwards target_cfg_version is {v} on the model's devices, so drift updates. Offline gateways take it when they reconnect.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ModelId"];
                    v: components["parameters"]["ConfigVersionNumber"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted; one job per gateway */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PushResult"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge an open alert (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The acknowledged alert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Fields the device page shows that DeviceDetail does not carry yet; merged into the DeviceDetail response. */
        DeviceExtras: {
            /** @example OpenWrt 23.05.4 */
            os?: string;
            /** @description Seconds since boot; null while offline */
            uptime_s?: number | null;
            interfaces?: components["schemas"]["InterfaceStatus"][];
        };
        InterfaceStatus: {
            type: string;
            identifier: string;
            /** @example wwan0 */
            name?: string;
            link_up?: boolean;
        };
        ActionRequest: {
            type: components["schemas"]["JobType"];
        };
        /** @enum {string} */
        JobType: "reboot" | "logs" | "ping";
        /** @enum {string} */
        JobState: "pending" | "running" | "succeeded" | "failed" | "timed_out" | "cancelled";
        Job: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["JobType"];
            sn: string;
            state: components["schemas"]["JobState"];
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Null until the state is final
             */
            finished_at: string | null;
            /** @description 0..100, for the logs upload */
            progress: number | null;
            /** @description Ping: "0% loss, avg 42 ms" */
            detail: string | null;
            /** @description Set when the job failed or timed out */
            error: {
                code: string;
                message: string;
            } | null;
        };
        JobLogs: {
            url: string;
            /** Format: date-time */
            expires_at: string;
        };
        PushPreview: {
            /** @description Active gateways of the model that would get the job */
            gateways: number;
            /** @description How many of those are offline right now */
            offline: number;
        };
        PushResult: {
            jobs: number;
        };
        /** @enum {string} */
        RolloutState: "running" | "soaking" | "paused" | "completed" | "aborted";
        /** @enum {string} */
        RolloutDeviceState: "waiting" | "downloading" | "installing" | "updated" | "rolled_back" | "needs_recovery" | "skipped" | "deferred";
        /** @description Gateways in the rollout by state; they add up to the rollout's size */
        RolloutCounters: {
            updated: number;
            in_progress: number;
            rolled_back: number;
            needs_recovery: number;
            skipped: number;
            deferred: number;
            waiting: number;
        };
        RolloutWave: {
            /** @description Share of the model's gateways updated once this wave finishes */
            percent: number;
            /** @description Present on GET /rollouts/{id} only */
            devices?: {
                sn: string;
                state: components["schemas"]["RolloutDeviceState"];
                /** @description Download progress 0..100 while state is downloading */
                progress?: number | null;
            }[];
        };
        Rollout: {
            /** @example R-014 */
            id: string;
            model_id: string;
            fw_version: string;
            /** Format: date-time */
            created_at: string;
            /** @description Name of the user who started it */
            created_by: string;
            state: components["schemas"]["RolloutState"];
            /** @description Why the rollout paused itself; null when paused by a person or running */
            pause_reason?: string | null;
            counters: components["schemas"]["RolloutCounters"];
            waves: components["schemas"]["RolloutWave"][];
        };
        /** @enum {string} */
        AlertSeverity: "info" | "warning" | "critical";
        Alert: {
            id: string;
            sn: string;
            /** @example temp_high */
            rule: string;
            severity: components["schemas"]["AlertSeverity"];
            /** @example Temperature 81 °C */
            message: string;
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            resolved_at: string | null;
            /** @description Name of the admin who acknowledged it */
            acked_by: string | null;
            /** Format: date-time */
            acked_at: string | null;
        };
        Error: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
    };
    responses: {
        /** @description Missing, invalid or expired credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with existing state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ModelId: string;
        ConfigVersionNumber: number;
        JobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
