/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login succeeded */
                200: {
                    headers: {
                        /** @description HttpOnly refresh token cookie, scoped to /api/v1/auth */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Invalid credentials or account locked */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh token cookie for a new access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie: {
                    gwf_refresh: string;
                };
            };
            requestBody?: never;
            responses: {
                /** @description Refresh succeeded */
                200: {
                    headers: {
                        /** @description Rotated HttpOnly refresh token cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    gwf_refresh?: string;
                };
            };
            requestBody?: never;
            responses: {
                /** @description Logged out (idempotent, always succeeds) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Create a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description User created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a user by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a user */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        /** Update a user's role */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description Updated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every gateway model */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of models */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Model"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a model */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateModelRequest"];
                };
            };
            responses: {
                /** @description Model created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Model"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a model's name */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateModelRequest"];
                };
            };
            responses: {
                /** @description Updated model */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Model"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every site */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of sites */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Site"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Create a site */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SiteRequest"];
                };
            };
            responses: {
                /** @description Site created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Site"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a site's name and vars */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SiteRequest"];
                };
            };
            responses: {
                /** @description Updated site */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Site"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        trace?: never;
    };
    "/models/{id}/configs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** List config versions for a model, newest first */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of config versions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigVersion"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Save a new config version (version = last + 1) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConfigVersionRequest"];
                };
            };
            responses: {
                /** @description Config version created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigVersion"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Text is identical to the latest version */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid UCI text (code config_invalid, details.line names the offending line) or missing note (code validation_failed) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/configs/{v}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                v: number;
            };
            cookie?: never;
        };
        /** Get a single config version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    v: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The config version */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfigVersion"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/configs/{v}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                v: number;
            };
            cookie?: never;
        };
        /** Line diff of version v against another version */
        get: {
            parameters: {
                query: {
                    against: number;
                };
                header?: never;
                path: {
                    id: string;
                    v: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Line-by-line diff */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiffOp"][];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/packages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Fleet package view of a model
         * @description Every package the model's gateways report (their model's report list), which versions run on how many gateways, and what each firmware release those gateways run expects (BE-08.2). Packages a manifest lists but no gateway reports are left out.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The fleet package view */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FleetPackages"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/firmware/{version}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                /** @description The firmware version gateways report (DISTRIB_RELEASE) */
                version: string;
            };
            cookie?: never;
        };
        /** Package list recorded for a firmware release */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    /** @description The firmware version gateways report (DISTRIB_RELEASE) */
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The manifest */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FirmwareManifest"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * Record the package list of a firmware release
         * @description The body is the image's OpenWrt .manifest as the build wrote it, one "<name> - <version>" per line (max 1 MiB). Recorded once per release: firmware releases are immutable, so a changed image is a new version (docs/contracts.md).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    /** @description The firmware version gateways report (DISTRIB_RELEASE) */
                    version: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example base-files - 1711~f5dae5ece4
                     *     gw-agent - 0.1.0-r1
                     */
                    "text/plain": string;
                };
            };
            responses: {
                /** @description Recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FirmwareManifestCreated"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                422: components["responses"]["UnprocessableEntity"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List, search and filter the fleet
         * @description Devices ordered by SN, paged with a cursor: pass the next_cursor of one page as the cursor of the next. Health and drift are computed from live state, never stored.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Model id */
                    model?: string;
                    /** @description Site id */
                    site?: string;
                    health?: components["schemas"]["Health"];
                    /** @description Only devices that have drifted, or only those in sync */
                    drift?: boolean;
                    /** @description Only devices whose reported packages differ from their firmware's manifest (true), or only those that do not (false); unknown counts as not drifted */
                    package_drift?: boolean;
                    /** @description SN prefix, site name, or an interface identifier (MAC, IMEI, ICCID) substring */
                    q?: string;
                    /** @description SN of the last device of the previous page */
                    cursor?: string;
                    /** @description Page size, default 50, maximum 200 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One page of devices */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceList"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description A filter value is malformed (code validation_failed), e.g. an unknown health, a non-uuid site or a limit below 1 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{sn}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sn: string;
            };
            cookie?: never;
        };
        /** One device, with its interfaces, metrics and config state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sn: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The device */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceDetail"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set a device's site and lifecycle */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sn: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DevicePatch"];
                };
            };
            responses: {
                /** @description The updated device */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceDetail"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Nothing to update, an unknown lifecycle, or a site that does not exist (code validation_failed) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/devices/{sn}/config/rendered": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sn: string;
            };
            cookie?: never;
        };
        /** The device's model's latest config version rendered for display: device and site variables substituted, secret values masked as "******". */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sn: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rendered config text and its hash */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RenderedConfig"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description Rendered config references variables with no value (code config_incomplete, details.missing lists every missing "namespace.key" name) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dl/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Self-contained signed link: it carries the bucket, the object key, the HTTP method it authorises, and an expiry, all covered by an HMAC-SHA256 signature. It is short by design, because the gateway's protobuf caps this URL at 256 bytes and a SigV4 presigned S3 URL cannot fit in that budget. */
                token: string;
            };
            cookie?: never;
        };
        /**
         * Download a stored object through a short-lived signed link
         * @description Self-authenticating: no Authorization header is read or required. The api streams the object from the internal object store, which gateways cannot reach directly. A link bound to PUT is rejected here even when its signature is valid.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Self-contained signed link: it carries the bucket, the object key, the HTTP method it authorises, and an expiry, all covered by an HMAC-SHA256 signature. It is short by design, because the gateway's protobuf caps this URL at 256 bytes and a SigV4 presigned S3 URL cannot fit in that budget. */
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description The link is forged, expired, or bound to another HTTP method. Every one of those cases answers identically, so the response cannot be used to probe which part of a guess was right. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * Upload a gateway log archive through a short-lived signed link
         * @description Self-authenticating and restricted to the logs bucket, so a link can never overwrite a firmware image. Content-Length is required: the api streams the body straight to the object store and never buffers it.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Self-contained signed link: it carries the bucket, the object key, the HTTP method it authorises, and an expiry, all covered by an HMAC-SHA256 signature. It is short by design, because the gateway's protobuf caps this URL at 256 bytes and a SigV4 presigned S3 URL cannot fit in that budget. */
                    token: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/gzip": string;
                };
            };
            responses: {
                /** @description Stored */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The link is forged, expired, bound to another method, or points at a bucket devices are not allowed to write. */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Content-Length is required */
                411: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The archive is larger than the upload limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
                details?: unknown;
            };
        };
        CursorPage: {
            next_cursor: string | null;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** @enum {string} */
            role: "viewer" | "release" | "admin";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            access_token: string;
            user: components["schemas"]["User"];
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            name: string;
            password: string;
            /** @enum {string} */
            role: "viewer" | "release" | "admin";
        };
        UpdateUserRequest: {
            /** @enum {string} */
            role: "viewer" | "release" | "admin";
        };
        Model: {
            id: string;
            name: string;
        };
        CreateModelRequest: {
            id: string;
            name: string;
        };
        UpdateModelRequest: {
            name: string;
        };
        Site: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description Flat object of string values */
            vars: {
                [key: string]: string;
            };
        };
        SiteRequest: {
            name: string;
            /** @description Flat object of string values */
            vars: {
                [key: string]: string;
            };
        };
        ConfigVersion: {
            version: number;
            text: string;
            note: string;
            /** Format: uuid */
            created_by?: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateConfigVersionRequest: {
            /** @description Rendered in `uci export` format */
            text: string;
            note: string;
        };
        DiffOp: {
            /** @enum {string} */
            op: "=" | "+" | "-";
            text: string;
        };
        RenderedConfig: {
            /** @description Rendered `uci export` text with device/site variables filled in and secret values masked as "******". */
            text: string;
            /** @description Lower-case hex SHA-256 of the rendered text */
            hash: string;
        };
        /**
         * @description Computed from live state, never stored: offline when the device is not online, critical at 80 °C or 90 % RAM, warning at 72 °C, 80 % RAM or under 8 MB free in /tmp, healthy otherwise.
         * @enum {string}
         */
        Health: "healthy" | "warning" | "critical" | "offline";
        HWInterface: {
            /** @example mac */
            type: string;
            /** @example AA:BB:CC:DD:EE:FF */
            identifier: string;
        };
        /** @description The newest telemetry sample the device reported. A null value is one the gateway did not report. */
        LastMetrics: {
            /** Format: date-time */
            time: string;
            cpu_pct?: number | null;
            mem_pct?: number | null;
            temp_c?: number | null;
            tmp_free_kb?: number | null;
            signal_dbm?: number | null;
            rx_bytes?: number | null;
            tx_bytes?: number | null;
        };
        Device: {
            sn: string;
            model_id: string;
            model_name: string;
            /**
             * Format: uuid
             * @description Null while the device is not assigned to a site
             */
            site_id?: string | null;
            site_name: string;
            /** @enum {string} */
            lifecycle: "active" | "decommissioned" | "bricked";
            hw_rev?: string;
            online: boolean;
            /** Format: date-time */
            last_seen?: string | null;
            fw_version?: string;
            /** @description Config version the device reported; null until it reports one */
            cfg_version?: number | null;
            /** @description Hash of the config the device reported running */
            cfg_hash?: string;
            /** @description Config version the device's model targets; null when nothing has been pushed to that model yet */
            target_cfg_version?: number | null;
            /** @description Target config version differs from the reported one */
            drift: boolean;
            health: components["schemas"]["Health"];
            /**
             * @description Reported packages against the manifest of the firmware the device runs; unknown when no manifest is recorded for it
             * @enum {string}
             */
            package_drift: "ok" | "drift" | "unknown";
        };
        DeviceList: {
            devices: components["schemas"]["Device"][];
            /** @description Pass as the cursor of the next request; absent on the last page */
            next_cursor?: string;
        };
        DeviceDetail: components["schemas"]["Device"] & {
            /** Format: date-time */
            created_at: string;
            interfaces: components["schemas"]["HWInterface"][];
            last_metrics?: components["schemas"]["LastMetrics"] | null;
            packages: components["schemas"]["PackageStatus"][];
        };
        PackageStatus: {
            name: string;
            /** @description The version the device reported */
            version: string;
            /** @description The version the device's firmware installs; empty when its manifest does not list the package or is unknown */
            expected: string;
            /** @enum {string} */
            status: "ok" | "drift" | "not_in_manifest" | "unknown";
        };
        FirmwareManifest: {
            model_id: string;
            fw_version: string;
            packages: {
                name: string;
                version: string;
            }[];
        };
        FirmwareManifestCreated: {
            model_id: string;
            fw_version: string;
            /** @description Number of packages recorded */
            packages: number;
        };
        FleetPackages: {
            model_id: string;
            packages: {
                name: string;
                /** @description What each firmware version the fleet runs installs */
                expected: {
                    fw_version: string;
                    version: string;
                }[];
                installed: {
                    fw_version: string;
                    version: string;
                    devices: number;
                    /** @enum {string} */
                    status: "ok" | "drift" | "not_in_manifest" | "unknown";
                }[];
            }[];
        };
        /** @description At least one field. An omitted field keeps its current value; an explicit null site_id unassigns the device. */
        DevicePatch: {
            /** Format: uuid */
            site_id?: string | null;
            /** @enum {string} */
            lifecycle?: "active" | "decommissioned" | "bricked";
        };
    };
    responses: {
        /** @description Malformed request body */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid or expired credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicts with existing state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A precondition (e.g. optimistic concurrency check) failed */
        PreconditionFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Semantically invalid request */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
